### ISSUE TITLE
OpenSource our custom plugin.

### ISSUE THREAD

**Issue by DanielRailean** [LEGO/kong-aws-request-signing#2]
We would like to make the plugin OpenSource to gain visibility and community support.

## Tasks to complete

- [x] Add a license to the [repository.](https://github.com/LEGO/kong-plugin-aws-sigv4-webid-auth)
- [x] Add comments with licenses of the libraries used in the plugin.
- [x] Tidy up plugin code.
- [x] Add Contributing Guide.
- [x] Add Open Source Code Attributions
- [x] Add Code of Conduct

## Acceptance Criteria

- [x] Plugin has Contribution Guide, Code of conduct, Open Source Code Attributions
- [x] The plugin is OpenSource
- [x] Our Legal Department is happy about it.

**Comment by giovannidegani** [comment]
I guess we can close this issue now :) Uhuu
